apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: test
spec:
  containers:
  - name: debug-container
    image: nicolaka/netshoot:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
