apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin-policy
  namespace: bar
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["foo"]
    to:
    - operation:
        methods: ["GET"]
  selector:
    matchLabels:
      app: httpbin
